kernel: sbalance: Fixup
../kernel/irq/sbalance.c:285:41: error: incompatible function pointer types passing 'int (void *, const struct list_head *, const struct list_head *)' to parameter of type 'int (*)(void *, struct list_head *, struct list_head *)' [-Werror,-Wincompatible-function-pointer-types]
        list_sort(NULL, &max_bd->movable_irqs, bal_irq_move_node_cmp);
                                               ^~~~~~~~~~~~~~~~~~~~~
../include/linux/list_sort.h:11:15: note: passing argument to parameter 'cmp' here
               int (*cmp)(void *priv, struct list_head *a,

Since the android12-5.10 branch is missing the following commit:
https://github.com/aosp-mirror/kernel_common/commit/55e6f8b3c0f5cc600df12ddd0371d2703b910fd7